apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjon-pol-innsyn-tp
  namespace: pensjonsamhandling
  labels:
    team: pensjonsamhandling
  annotations:
    config.linkerd.io/proxy-outbound-connect-timeout: "3s"
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - https://pensjon-pol-innsyn-tp.intern.dev.nav.no
  accessPolicy:
    outbound:
      external:
        - host: tp-api-q1.dev-fss-pub.nais.io
  azure:
    application:
      enabled: true
      replyURLs:
        - https://pensjon-pol-innsyn-tp.intern.dev.nav.no/login/oauth2/code/azure
      claims:
        extra:
          - NAVident
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
  liveness:
    path: actuator/health/liveness
    initialDelay: 45
    periodSeconds: 1
    failureThreshold: 60
  readiness:
    path: actuator/health/readiness
    initialDelay: 45
    periodSeconds: 1
    failureThreshold: 60
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  prometheus:
    enabled: true
    path: actuator/prometheus
