apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjon-pol-innsyn-tp
  namespace: default
  labels:
    team: pensjonsamhandling
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - https://pensjon-pol-innsyn-tp.nais.preprod.local
  liveness:
    path: actuator/health/liveness
  readiness:
    path: actuator/health/readiness
  vault:
    enabled: true
    paths:
      - mountPath: /secrets/oracle/tp-registeret
        kvPath: oracle/data/dev/creds/tjenestepensjon_q0-user
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  prometheus:
    enabled: true
    path: actuator/prometheus
