apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjon-pol-innsyn-tp
  namespace: pensjonsamhandling
  labels:
    team: pensjonsamhandling
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - https://pensjon-pol-innsyn-tp.nais.preprod.local
  azure:
    application:
      enabled: true
      claims:
        extra:
          - NAVident
    sidecar:
      enabled: false
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
  liveness:
    path: actuator/health/liveness
    initialDelay: 30
    periodSeconds: 1
    failureThreshold: 60
  readiness:
    path: actuator/health/readiness
    initialDelay: 30
    periodSeconds: 1
    failureThreshold: 60
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  prometheus:
    enabled: true
    path: actuator/prometheus
