management:
  endpoints.web.exposure.include: prometheus, health
  endpoint:
    prometheus:
      access: read_only
spring:
  cloud.azure.active-directory:
    enabled: true
    application-type: web_application_and_resource_server
    authorization-clients:
      tp:
        authorization-grant-type: on_behalf_of
        scopes:
          - ${tp.scope}
    credential:
      client-id: ${AZURE_APP_CLIENT_ID}
      client-secret: ${AZURE_APP_CLIENT_SECRET}
    profile:
      tenant-id: ${AZURE_APP_TENANT_ID}
