management:
  endpoint.prometheus.enabled: true
  endpoints.web.exposure.include: prometheus, health
spring.security.oauth2.client.registration.isso:
  authorization-grant-type: authorization_code
  client-id: ${client uuid}
  client-name: ISSO
  client-secret: ${client secret}
  provider: isso
  scope: openid