management:
  endpoint.prometheus.enabled: true
  endpoints.web.exposure.include: prometheus, health
spring.security.oauth2.client:
  registration.azure:
    authorization-grant-type: authorization_code
    client-id: ${AZURE_APP_CLIENT_ID}
    client-name: Azure
    client-secret: ${AZURE_APP_CLIENT_SECRET}
    provider: azure
    scope: openid
