management:
  endpoint.prometheus.enabled: true
  endpoints.web.exposure.include: prometheus, health
no.nav.security.jwt.issuer.sts:
  discoveryUrl: http://security-token-service/.well-known/openid-configuration
  accepted_audience: preprod.local,srvpensjon