apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjon-pol-innsyn-tp
  namespace: pensjonsamhandling
  labels:
    team: pensjonsamhandling
  annotations:
    config.linkerd.io/proxy-outbound-connect-timeout: "3s"
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - https://pensjon-pol-innsyn-tp.intern.nav.no
  accessPolicy:
    outbound:
      external:
        - host: tp-api.prod-fss-pub.nais.io
  azure:
    application:
      enabled: true
      replyURLs:
        - https://pensjon-pol-innsyn-tp.intern.nav.no/login/oauth2/code/azure
      claims:
        groups:
          - id: "457e28b8-7bc1-4c84-b5c8-404025dd096a" #Pensjon-samhandling
          - id: "5607faef-5fd9-4cbe-8842-a9d79cd78cbc" #NAV Kontaktsenter Oslo og Vest-Viken (Gammel?)
          - id: "29d85700-0eb1-483e-b12a-743c38dc37c0" #NAV Kontaktsenter Oslo of Vest-Viken 4106
        extra:
          - NAVident
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
  liveness:
    path: actuator/health/liveness
    initialDelay: 45
    periodSeconds: 1
    failureThreshold: 60
  readiness:
    path: actuator/health/readiness
    initialDelay: 45
    periodSeconds: 1
    failureThreshold: 60
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  prometheus:
    enabled: true
    path: actuator/prometheus
