CREATE TABLE T_PERSON
(
    PERSON_ID      NUMBER       NOT NULL UNIQUE,
    FNR_FK         VARCHAR2(11) NOT NULL,
    DATO_OPPRETTET TIMESTAMP(6) NOT NULL,
    OPPRETTET_AV   VARCHAR2(20) NOT NULL,
    DATO_ENDRET    TIMESTAMP(6) NOT NULL,
    ENDRET_AV      VARCHAR2(20) NOT NULL,
    VERSJON        NUMBER       NOT NULL
);

CREATE TABLE T_FORHOLD
(
    FORHOLD_ID         NUMBER            NOT NULL UNIQUE,
    PERSON_ID          NUMBER            NOT NULL,
    DATO_SAMTYKKE_GITT DATE,
    TSS_EKSTERN_ID_FK  VARCHAR2(25 BYTE) NOT NULL,
    DATO_OPPRETTET     TIMESTAMP(6)      NOT NULL,
    OPPRETTET_AV       VARCHAR2(20 BYTE) NOT NULL,
    DATO_ENDRET        TIMESTAMP(6)      NOT NULL,
    HAR_UTLAND_PENSJ   CHAR(1 BYTE)      NOT NULL,
    ENDRET_AV          VARCHAR2(20 BYTE) NOT NULL,
    K_KILDE_TP_T       VARCHAR2(20 BYTE) NOT NULL,
    VERSJON            NUMBER            NOT NULL,
    ER_GYLDIG          CHAR(1 BYTE)      NOT NULL,
    K_SAMTYKKE_SIM_T   VARCHAR2(20 BYTE) NOT NULL,
    HAR_SIMULERING     CHAR(1 BYTE)      NOT NULL,
    FUNK_FORHOLD_ID    NUMBER            NOT NULL,
    DATO_BRUK_FOM      TIMESTAMP(6)      NOT NULL,
    DATO_BRUK_TOM      TIMESTAMP(6)
);

CREATE TABLE T_YTELSE
(
    YTELSE_ID          NUMBER            NOT NULL UNIQUE,
    DATO_INNM_YTEL_FOM DATE,
    K_YTELSE_T         VARCHAR2(20 BYTE) NOT NULL,
    K_MELDING_T        VARCHAR2(20 BYTE),
    DATO_YTEL_IVER_FOM DATE,
    DATO_YTEL_IVER_TOM DATE,
    DATO_OPPRETTET     TIMESTAMP(6)      NOT NULL,
    OPPRETTET_AV       VARCHAR2(20 BYTE) NOT NULL,
    DATO_ENDRET        TIMESTAMP(6)      NOT NULL,
    ENDRET_AV          VARCHAR2(20 BYTE) NOT NULL,
    VERSJON            NUMBER            NOT NULL,
    ER_GYLDIG          CHAR(1 BYTE)      NOT NULL,
    FUNK_YTELSE_ID     NUMBER            NOT NULL,
    DATO_BRUK_FOM      TIMESTAMP(6)      NOT NULL,
    DATO_BRUK_TOM      TIMESTAMP(6)
);

CREATE TABLE T_TSS_TP
(
    TSS_ID VARCHAR2(20 BYTE) NOT NULL UNIQUE,
    TP_ID  VARCHAR2(20 BYTE),
    ORGNR  VARCHAR2(20 BYTE),
    NAVN   VARCHAR2(50 BYTE)
);

CREATE TABLE T_FORHOLD_YTELSE_HISTORIKK
(
    FORHOLD_ID_FK NUMBER NOT NULL,
    YTELSE_ID_FK  NUMBER NOT NULL
);