name: Build and Deploy Main

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-main:
    name: Build and Deploy Main
    permissions:
      contents: read
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v4
      - name: Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle

      # Build
      - name: Build
        run: gradle clean xjc build
        env:
          GITHUB_TOKEN: ${{ secrets.GITH_ACCESS_TOKEN }}

      # Build image
      - name: Nais docker-build
        uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: pensjonsamhandling
          tag: ${{ github.event.repository.name }}-main
          pull: true

        # Deploy
      - name: Deploy to dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais/dev.yaml
          IMAGE: ${{ steps.docker-push.outputs.image }}

      - name: Deploy to prod-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais/prod.yaml
          IMAGE: ${{ steps.docker-push.outputs.image }}
