name: Release to GitHub Package Registry

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: '18.x'

      # Build
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: build

      # Build image
      - name: Create tag
        run: echo "TAG=$(date "+%Y.%m.%d")-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push docker image
        uses: docker/build-push-action@v4.1.1
        with:
          username: token
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: navikt/pensjon-pol-innsyn-tp/pensjon-pol-innsyn-tp
          tags: ${{ env.TAG }}
