name: Run tests

on:
  pull_request:

jobs:
  build_and_release:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 18

      # Build
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: current
          arguments: build
