name: Run tests

on:
  pull_request:

jobs:
  build_and_release:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: '18.x'

      # Build
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: build
