name: Run tests

on:
  pull_request:

jobs:
  build_and_release:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      # Test
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: current
      - name: Build with Gradle
        run: gradle test
